-- CreateTable
CREATE TABLE `ROL` (
    `ID_ROL` INTEGER NOT NULL AUTO_INCREMENT,
    `ROL` VARCHAR(191) NOT NULL,
    `ESTADO` BOOLEAN NOT NULL,

    PRIMARY KEY (`ID_ROL`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TIPO_DOCUMENTO` (
    `ID_TIPO_DOCUMENTO` INTEGER NOT NULL AUTO_INCREMENT,
    `DOCUMENTO` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`ID_TIPO_DOCUMENTO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `USUARIO` (
    `ID_USUARIO` INTEGER NOT NULL AUTO_INCREMENT,
    `FK_ROL` INTEGER NOT NULL,
    `USUARIO` VARCHAR(191) NOT NULL,
    `CLAVE` TEXT NOT NULL,
    `ESTADO` BOOLEAN NOT NULL,

    PRIMARY KEY (`ID_USUARIO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PERSONA` (
    `ID_PERSONA` INTEGER NOT NULL AUTO_INCREMENT,
    `FK_USUARIO` INTEGER NOT NULL,
    `FK_TIPO_DOCUMENTO` INTEGER NOT NULL,
    `DOCUMENTO` VARCHAR(11) NOT NULL,
    `NOMBRES` VARCHAR(191) NOT NULL,
    `APELLIDOS` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`ID_PERSONA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `USUARIO` ADD CONSTRAINT `USUARIO_FK_ROL_fkey` FOREIGN KEY (`FK_ROL`) REFERENCES `ROL`(`ID_ROL`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PERSONA` ADD CONSTRAINT `PERSONA_FK_USUARIO_fkey` FOREIGN KEY (`FK_USUARIO`) REFERENCES `USUARIO`(`ID_USUARIO`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PERSONA` ADD CONSTRAINT `PERSONA_FK_TIPO_DOCUMENTO_fkey` FOREIGN KEY (`FK_TIPO_DOCUMENTO`) REFERENCES `TIPO_DOCUMENTO`(`ID_TIPO_DOCUMENTO`) ON DELETE RESTRICT ON UPDATE CASCADE;
